# Generated by Django 4.2.6 on 2023-11-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=20)),
                ('players_age', models.CharField(max_length=100)),
                ('native_place', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('no_of_winnings', models.IntegerField()),
            ],
        ),
    ]
